-- INVENTARIO DE BOTIQUÍN / SUPABASE
-- Ejecuta este archivo completo en Supabase > SQL Editor.
create table if not exists public.botiquines (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  fecha date,
  responsable text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventario_items (
  id bigint generated by default as identity primary key,
  botiquin_id bigint not null references public.botiquines(id) on delete cascade,
  no_item integer not null,
  categoria text not null,
  nombre text not null,
  unidad text,
  minimo integer not null default 1,
  existencia integer,
  caducidad date,
  updated_at timestamptz not null default now(),
  unique(botiquin_id, no_item)
);

alter table public.botiquines enable row level security;
alter table public.inventario_items enable row level security;

-- Para un equipo interno con usuarios autenticados:
drop policy if exists "botiquines_select_authenticated" on public.botiquines;
create policy "botiquines_select_authenticated"
on public.botiquines for select to authenticated using (true);

drop policy if exists "botiquines_insert_authenticated" on public.botiquines;
create policy "botiquines_insert_authenticated"
on public.botiquines for insert to authenticated with check (true);

drop policy if exists "botiquines_update_authenticated" on public.botiquines;
create policy "botiquines_update_authenticated"
on public.botiquines for update to authenticated using (true) with check (true);

drop policy if exists "items_select_authenticated" on public.inventario_items;
create policy "items_select_authenticated"
on public.inventario_items for select to authenticated using (true);

drop policy if exists "items_insert_authenticated" on public.inventario_items;
create policy "items_insert_authenticated"
on public.inventario_items for insert to authenticated with check (true);

drop policy if exists "items_update_authenticated" on public.inventario_items;
create policy "items_update_authenticated"
on public.inventario_items for update to authenticated using (true) with check (true);

-- Índices
create index if not exists inventario_items_botiquin_idx on public.inventario_items(botiquin_id);
create index if not exists inventario_items_categoria_idx on public.inventario_items(categoria);
